apiVersion: v1
kind: Service
metadata:
  name: ml-tree-system
  namespace: ml-system
  labels:
    app: ml-tree-system
spec:
  type: LoadBalancer
  selector:
    app: ml-tree-system
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
    name: http
  sessionAffinity: ClientIP
